const config=window.NIGHTAZIMUTH_CONFIG||{};const apiBase=String(config.apiBaseUrl||"").replace(/\/$/,"");const statusEl=document.querySelector("#api-status");const form=document.querySelector("#observer-form");const fovForm=document.querySelector("#fov-form");const fovInput=document.querySelector("#fov-input");const bearingForm=document.querySelector("#bearing-form");const bearingInput=document.querySelector("#bearing-input");const canvas=document.querySelector("#sky-canvas");const ctx=canvas.getContext("2d");let refreshGeneration=0;let aircraftFeatures=[];let skyAircraft=[];let skySatellites=[];let skyAirports=[];let celestialSky={stars:[],planets:[],galaxies:[],constellation_lines:[]};let fov=120;let facing=0;let hitTargets=[];let elevationCentre=45;const layers={stars:true,constellations:true,galaxies:true,planets:true,airports:true,aircraft:true,satellites:true};let drag=null;let dragMoved=false;let trackedObject=null;
function setText(s,v){document.querySelector(s).textContent=v}
function makeUrl(path,params={}){const target=new URL(apiBase+path);Object.entries(params).forEach(([k,v])=>target.searchParams.set(k,v));return target}
async function getJson(path,params,{timeoutMs=75000,retries=1}={}){let lastError;for(let attempt=0;attempt<=retries;attempt++){const controller=new AbortController();const timeout=setTimeout(()=>controller.abort(),timeoutMs);try{const response=await fetch(makeUrl(path,params),{headers:{Accept:"application/json, application/geo+json"},signal:controller.signal});if(!response.ok)throw new Error(String(response.status));return await response.json()}catch(error){lastError=error;if(attempt<retries)await new Promise(resolve=>setTimeout(resolve,1500))}finally{clearTimeout(timeout)}}throw lastError}
function observer(){return{latitude:document.querySelector("#latitude").value,longitude:document.querySelector("#longitude").value}}
function angularDifference(angle,centre){return((angle-centre+540)%360)-180}
function resizeSky(){const dpr=Math.min(window.devicePixelRatio||1,2);canvas.width=Math.round(innerWidth*dpr);canvas.height=Math.round(innerHeight*dpr);canvas.style.width=innerWidth+"px";canvas.style.height=innerHeight+"px";ctx.setTransform(dpr,0,0,dpr,0,0);drawSky()}
function drawSky(){updateTrackedView();hitTargets=[];const w=innerWidth,h=innerHeight;ctx.clearRect(0,0,w,h);const g=ctx.createRadialGradient(w*.5,h*.35,0,w*.5,h*.35,Math.max(w,h)*.8);g.addColorStop(0,"#10253a");g.addColorStop(.48,"#07111d");g.addColorStop(1,"#02050a");ctx.fillStyle=g;ctx.fillRect(0,0,w,h);ctx.strokeStyle="rgba(111,211,238,.14)";ctx.fillStyle="rgba(166,220,235,.58)";ctx.font="10px ui-monospace,monospace";for(let e=0;e<=60;e+=10){const y=h*.82-(e/60)*h*.62;ctx.beginPath();ctx.moveTo(w*.06,y);ctx.lineTo(w*.94,y);ctx.stroke();ctx.fillText(e+"°",w*.025,y+3)}for(let i=-2;i<=2;i++){const x=w*.5+(i/4)*w*.88;ctx.beginPath();ctx.moveTo(x,h*.2);ctx.lineTo(x,h*.82);ctx.stroke()}ctx.strokeStyle="rgba(111,211,238,.34)";ctx.beginPath();ctx.moveTo(w*.04,h*.82);ctx.lineTo(w*.96,h*.82);ctx.stroke();ctx.fillStyle="rgba(205,241,249,.7)";ctx.textAlign="center";ctx.fillText("HORIZON",w*.5,h*.805);drawCelestial(w,h);drawAirports(w,h);drawContacts(w,h)}
function skyXY(az,el,w,h){const off=angularDifference(az,facing);const verticalFov=Math.min(90,fov*h/Math.max(w,1));const elOff=el-elevationCentre;if(Math.abs(off)>fov/2||Math.abs(elOff)>verticalFov/2||el<0||el>90)return null;return [w*.06+(.5+off/fov)*w*.88,h*.5-(elOff/verticalFov)*h*.9]}
function hit(kind,item,p,r=10){hitTargets.push({kind,item,x:p[0],y:p[1],r})}
function drawCelestial(w,h){ctx.save();if(layers.constellations)for(const line of celestialSky.constellation_lines||[]){const a=skyXY(line.start_azimuth_deg,line.start_elevation_deg,w,h),b=skyXY(line.end_azimuth_deg,line.end_elevation_deg,w,h);if(!a||!b)continue;ctx.strokeStyle="rgba(130,180,220,.18)";ctx.beginPath();ctx.moveTo(...a);ctx.lineTo(...b);ctx.stroke()}if(layers.stars)for(const s of celestialSky.stars||[]){const p=skyXY(s.azimuth_deg,s.elevation_deg,w,h);if(!p)continue;const r=Math.max(.7,3.2-(Number(s.magnitude)+1)*.38);ctx.fillStyle="rgba(225,242,255,.9)";ctx.beginPath();ctx.arc(p[0],p[1],r,0,Math.PI*2);ctx.fill();hit("star",s,p,Math.max(8,r+4))}if(layers.galaxies)for(const g of celestialSky.galaxies||[]){const p=skyXY(g.azimuth_deg,g.elevation_deg,w,h);if(!p)continue;ctx.strokeStyle="rgba(178,150,255,.75)";ctx.beginPath();ctx.ellipse(p[0],p[1],7,3,0,0,Math.PI*2);ctx.stroke();ctx.fillStyle="rgba(220,205,255,.85)";ctx.font="9px ui-monospace,monospace";ctx.fillText(g.name,p[0]+9,p[1]-5);hit("galaxy",g,p,12)}if(layers.planets)for(const pnt of celestialSky.planets||[]){const p=skyXY(pnt.azimuth_deg,pnt.elevation_deg,w,h);if(!p)continue;ctx.fillStyle="#fff0ad";ctx.beginPath();ctx.arc(p[0],p[1],4,0,Math.PI*2);ctx.fill();ctx.font="10px ui-monospace,monospace";ctx.fillText(pnt.name,p[0]+8,p[1]-6);hit("planet",pnt,p,12)}ctx.restore()}

function drawAirports(w,h){if(!layers.airports)return;for(const airport of skyAirports){const off=angularDifference(Number(airport.bearing_deg),facing);if(Math.abs(off)>fov/2)continue;const x=w*.06+(.5+off/fov)*w*.88,y=h*.805;ctx.save();ctx.strokeStyle="rgba(112,255,191,.85)";ctx.fillStyle="rgba(190,255,225,.95)";ctx.beginPath();ctx.moveTo(x,y);ctx.lineTo(x,y-16);ctx.stroke();ctx.beginPath();ctx.arc(x,y-18,3,0,Math.PI*2);ctx.fill();ctx.font="10px ui-monospace,monospace";ctx.textAlign="center";ctx.fillText((airport.iata||airport.icao)+" · "+Math.round(airport.distance_km)+"km",x,y-25);ctx.restore();hit("airport",airport,[x,y-18],16)}}
function drawContacts(w,h){if(layers.aircraft)for(const p of skyAircraft){const az=Number(p.azimuth_deg);const el=Number(p.elevation_deg);if(!Number.isFinite(az)||!Number.isFinite(el))continue;const point=skyXY(az,el,w,h);if(!point)continue;const [x,y]=point;const special=p.display?.special||p.military;const selected=trackedObject?.kind==="aircraft"&&trackedObject.key===p.icao24;ctx.shadowBlur=selected?28:(special?18:12);ctx.shadowColor=selected?"#ffffff":(special?"#f59e0b":"#42d9ff");ctx.fillStyle=selected?"#ffffff":(special?"#ffd166":"#8be9ff");ctx.beginPath();ctx.arc(x,y,selected?6:3.5,0,Math.PI*2);ctx.fill();ctx.shadowBlur=0;ctx.fillStyle="#dff8ff";ctx.textAlign="left";ctx.font="10px ui-monospace,monospace";ctx.fillText((p.display?.role?`${p.display.role} · `:"")+(p.callsign||p.icao24||"AIR"),x+8,y-7);hit("aircraft",p,[x,y],14)}if(layers.satellites)for(const p of skySatellites){const az=Number(p.azimuth_deg);const el=Number(p.elevation_deg);if(!Number.isFinite(az)||!Number.isFinite(el))continue;const point=skyXY(az,el,w,h);if(!point)continue;const [x,y]=point;ctx.strokeStyle="#ffd76a";ctx.fillStyle="#ffd76a";ctx.beginPath();ctx.moveTo(x,y-5);ctx.lineTo(x+5,y);ctx.lineTo(x,y+5);ctx.lineTo(x-5,y);ctx.closePath();ctx.stroke();ctx.font="10px ui-monospace,monospace";ctx.textAlign="left";ctx.fillText(p.name||"SAT",x+8,y-7);hit("satellite",p,[x,y],12)}}
function renderContacts(data){aircraftFeatures=data.features||[];drawSky();const root=document.querySelector("#contacts");if(!skyAircraft.length){root.textContent="No aircraft contacts returned for this area.";return}root.replaceChildren(...skyAircraft.slice(0,20).map(aircraft=>{const row=document.createElement("button");row.type="button";row.className="contact contact-button";const name=document.createElement("strong");name.textContent=(aircraft.display?.role?aircraft.display.role+" · ":"")+(aircraft.callsign||aircraft.registration||aircraft.icao24||"Unknown");const detail=document.createElement("span");detail.textContent=`${Math.round(aircraft.altitude_m||0)} m · ${aircraft.display?.make_model||aircraft.type_description||aircraft.type_code||aircraft.position_state||"unknown"}`;row.append(name,detail);row.addEventListener("click",()=>focusAircraft(aircraft));return row}))}

function trackingKey(kind,item){return kind==="aircraft"?item.icao24:kind==="satellite"?(item.norad_id||item.name):kind==="star"?(item.hip_id||item.name):kind==="planet"?item.name:null}
function findTrackedItem(){if(!trackedObject)return null;const sources={aircraft:skyAircraft,satellite:skySatellites,star:celestialSky.stars||[],planet:celestialSky.planets||[]};return (sources[trackedObject.kind]||[]).find(item=>trackingKey(trackedObject.kind,item)===trackedObject.key)||null}
function updateTrackedView(){const item=findTrackedItem();if(!item)return;const az=Number(item.azimuth_deg),el=Number(item.elevation_deg);if(Number.isFinite(az))facing=az;if(Number.isFinite(el))elevationCentre=Math.max(0,Math.min(90,el));bearingInput.value=String(Math.round(facing)%360)}
function pointerPosition(event){return{x:event.clientX,y:event.clientY}}
canvas.addEventListener("pointerdown",event=>{if(trackedObject)return;dragMoved=false;drag={...pointerPosition(event),facing,elevationCentre};canvas.setPointerCapture(event.pointerId);canvas.style.cursor="grabbing"});
canvas.addEventListener("pointermove",event=>{if(!drag)return;const p=pointerPosition(event);if(Math.hypot(p.x-drag.x,p.y-drag.y)>4)dragMoved=true;facing=(drag.facing-(p.x-drag.x)/Math.max(canvas.clientWidth,1)*fov+360)%360;const verticalFov=Math.min(90,fov*canvas.clientHeight/Math.max(canvas.clientWidth,1));elevationCentre=Math.max(0,Math.min(90,drag.elevationCentre+(p.y-drag.y)/Math.max(canvas.clientHeight,1)*verticalFov));bearingInput.value=String(Math.round(facing)%360);drawSky()});
function endDrag(event){if(!drag)return;drag=null;canvas.style.cursor="grab";try{canvas.releasePointerCapture(event.pointerId)}catch{}}
canvas.addEventListener("pointerup",endDrag);canvas.addEventListener("pointercancel",endDrag);canvas.style.cursor="grab";
document.querySelectorAll("[data-layer]").forEach(input=>input.addEventListener("change",()=>{layers[input.dataset.layer]=input.checked;drawSky()}));

function focusAircraft(aircraft){trackedObject={kind:"aircraft",key:trackingKey("aircraft",aircraft)};facing=Number(aircraft.azimuth_deg);elevationCentre=Math.max(0,Math.min(90,Number(aircraft.elevation_deg)));bearingInput.value=String(Math.round(facing)%360);showObject({kind:"aircraft",item:aircraft});drawSky()}\nfunction zoomBy(delta){fov=Math.max(5,Math.min(180,fov*delta));fovInput.value=String(Math.round(fov));setText("#fov-readout",`${Math.round(fov)}°`);drawSky()}
canvas.addEventListener("wheel",event=>{event.preventDefault();zoomBy(event.deltaY<0?.85:1.18)},{passive:false});
let pinchDistance=null;canvas.addEventListener("touchmove",event=>{if(event.touches.length!==2)return;const [a,b]=event.touches;const distance=Math.hypot(a.clientX-b.clientX,a.clientY-b.clientY);if(pinchDistance)zoomBy(pinchDistance/distance);pinchDistance=distance},{passive:false});canvas.addEventListener("touchend",()=>{pinchDistance=null});
const inspector=document.querySelector("#object-inspector");document.querySelector("#inspector-close").addEventListener("click",()=>inspector.hidden=true);
function toggleTracking(target){if(!["aircraft","satellite","star","planet"].includes(target.kind))return false;const key=trackingKey(target.kind,target.item);if(key==null)return false;if(trackedObject?.kind===target.kind&&trackedObject?.key===key){trackedObject=null;return true}trackedObject={kind:target.kind,key};facing=Number(target.item.azimuth_deg);elevationCentre=Math.max(0,Math.min(90,Number(target.item.elevation_deg)));bearingInput.value=String(Math.round(facing)%360);return true}
function showObject(target){const raw=target.item;const item=target.kind==="aircraft"?{...raw,role:raw.display?.role,make_model:raw.display?.make_model,capacity:raw.display?.capacity,special_squawk:raw.display?.squawk}:raw;setText("#inspector-type",target.kind.toUpperCase());setText("#inspector-name",item.name||item.callsign||item.registration||item.icao24||(`HIP ${item.hip_id||"—"}`));const labels={role:"Role",make_model:"Aircraft",capacity:"Capacity",special_squawk:"Squawk / operation",military:"Military",iata:"IATA",icao:"ICAO",bearing_deg:"Bearing",distance_km:"Distance (km)",azimuth_deg:"Azimuth",elevation_deg:"Elevation",magnitude:"Magnitude",callsign:"Callsign",icao24:"ICAO24",registration:"Registration",type_code:"Aircraft type",type_description:"Description",operator:"Operator",altitude_m:"Altitude",ground_speed_mps:"Ground speed",track_deg:"Track",vertical_rate_mps:"Vertical rate",squawk:"Squawk",distance_km:"Distance",norad_id:"NORAD ID"};const details=document.querySelector("#inspector-details");details.replaceChildren(...Object.entries(labels).filter(([key])=>item[key]!=null).map(([key,label])=>{const row=document.createElement("div");const k=document.createElement("span");k.textContent=label;const v=document.createElement("strong");v.textContent=String(item[key]);row.append(k,v);return row}));inspector.hidden=false}
canvas.addEventListener("click",event=>{if(dragMoved)return;const rect=canvas.getBoundingClientRect(),x=event.clientX-rect.left,y=event.clientY-rect.top;let best=null,bestD=Infinity;for(const target of hitTargets){const d=Math.hypot(x-target.x,y-target.y);if(d<=target.r&&d<bestD){best=target;bestD=d}}if(best){toggleTracking(best);showObject(best);drawSky()}});
function applyBearing(){const value=Number(bearingInput.value);if(!Number.isFinite(value)||value<0||value>=360){bearingInput.setCustomValidity("Enter a facing from 0° to 359°.");bearingInput.reportValidity();return}bearingInput.setCustomValidity("");trackedObject=null;facing=value;drawSky()}
function applyFov(){const value=Number(fovInput.value);if(!Number.isFinite(value)||value<5||value>180){fovInput.setCustomValidity("Enter a field of view from 5° to 180°.");fovInput.reportValidity();return}fovInput.setCustomValidity("");fov=value;setText("#fov-readout",`${Math.round(fov)}°`);drawSky()}


let refreshInFlight=false;async function refresh(){if(refreshInFlight)return;refreshInFlight=true;const generation=++refreshGeneration;if(!apiBase){statusEl.textContent="Set apiBaseUrl in config.js";refreshInFlight=false;return}statusEl.textContent="SYNCING";const pos=observer();let failures=0;const tasks=[
getJson("/api/v1/aircraft",{...pos,radius_km:200,minimum_elevation_deg:-90,include_ground:true},{timeoutMs:20000,retries:0}).then(data=>{if(generation!==refreshGeneration)return;skyAircraft=data.aircraft||[];setText("#aircraft-count",data.count??skyAircraft.length);setText("#aircraft-detail",data.source?.label||"Live aircraft");setText("#updated",data.observed_at||"Loaded");renderContacts(data.geojson||{features:[]});drawSky()}).catch(()=>{failures++;setText("#aircraft-count","—");setText("#aircraft-detail","Aircraft unavailable")}),
getJson("/api/v1/airports",{...pos,radius_km:160.934,limit:12},{timeoutMs:12000,retries:0}).then(data=>{if(generation!==refreshGeneration)return;skyAirports=data.airports||[];drawSky()}).catch(()=>{failures++}),
getJson("/api/v1/weather",pos,{timeoutMs:20000,retries:0}).then(data=>{if(generation!==refreshGeneration)return;const current=data.current||{};setText("#weather-value",current.air_temperature_c==null?"LIVE":`${current.air_temperature_c}°C`);setText("#weather-detail",current.cloud_total_percent==null?"Weather snapshot available":`${current.cloud_total_percent}% cloud cover`)}).catch(()=>{failures++;setText("#weather-value","—");setText("#weather-detail","Weather unavailable")}),
getJson("/api/v1/observing",pos,{timeoutMs:20000,retries:0}).then(data=>{if(generation!==refreshGeneration)return;const first=(data.guidance||[])[0];setText("#observing-value",first?.rating||"LIVE");setText("#observing-detail",first?.confidence?`Observing confidence: ${first.confidence}`:"Observing guidance available")}).catch(()=>{failures++;setText("#observing-value","—");setText("#observing-detail","Observing guidance unavailable")}),
getJson("/api/v1/sky",pos,{timeoutMs:30000,retries:0}).then(data=>{if(generation!==refreshGeneration)return;celestialSky=data;drawSky()}).catch(()=>{failures++}),
getJson("/api/v1/satellites",{...pos,minimum_elevation_deg:0},{timeoutMs:12000,retries:0}).then(data=>{if(generation!==refreshGeneration)return;skySatellites=data.satellites||[];setText("#satellite-count",data.count??skySatellites.length);drawSky()}).catch(()=>{failures++;setText("#satellite-count",skySatellites.length?`${skySatellites.length} stale`:"—")})
];await Promise.allSettled(tasks);if(generation===refreshGeneration)statusEl.textContent=failures===tasks.length?"API UNAVAILABLE":failures?`LIVE · ${failures} SERVICE ISSUE${failures===1?"":"S"}`:"● LIVE";refreshInFlight=false}
form.addEventListener("submit",event=>{event.preventDefault();refresh().catch(()=>{refreshInFlight=false;statusEl.textContent="API UNAVAILABLE"})});fovForm.addEventListener("submit",event=>{event.preventDefault();applyFov()});bearingForm.addEventListener("submit",event=>{event.preventDefault();applyBearing()});window.addEventListener("resize",resizeSky);resizeSky();

// Load a useful default sky immediately; users can replace these coordinates at any time.
const latInput=document.querySelector("#latitude");const lonInput=document.querySelector("#longitude");
if(!latInput.value)latInput.value="55.764";if(!lonInput.value)lonInput.value="-4.177";
refresh().catch(()=>{refreshInFlight=false;statusEl.textContent="API UNAVAILABLE"});
setInterval(()=>refresh().catch(()=>{refreshInFlight=false;statusEl.textContent="API UNAVAILABLE"}),60000);
